services:
  postgres:
    image: postgres:17-alpine
    container_name: alten-postgres
    environment:
      POSTGRES_DB: alten
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - alten-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: alten-app
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/alten
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      DEBUG: "false"
      DEBUG_PORT: "5005"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - alten-network

volumes:
  postgres_data:

networks:
  alten-network:
    driver: bridge
